server:
  port: 9527
  
spring:  application:    name: zuul-gateway
   
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost1.com:7001/eureka/,http://localhost2.com:7002/eureka/,http://localhost3.com:7003/eureka/   
  instance:
    instance-id: zuul-gateway9527       #服务器名称修改
    prefer-ip-address: true             #服务器显示IP地址
    
info:
  name: zuul-gateway 