server:
  port: 7002
  
eureka:  instance:    hostname: localhost2.com         #eureka服务端的实例名称
    
  client:    register-with-eureka: false #不向注册中心注册自己
    fetch-registry: false       #自己就是注册中心,不需要去检索服务
    service-url:      defaultZone: http://localhost1.com:7001/eureka/,http://localhost3.com:7003/eureka/   #设置与eureka server查询,注册服务的交互地址