server:
  port: 8001
  
mybatis:  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.inus.ms.entities
  mapper-locations:  - classpath:mybatis/mapper/**/*.xml
  
spring:  application:    name: ms
  datasource:    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mscloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: root
    dbcp2:      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
  